// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: business.proto

/*
Package business is a generated protocol buffer package.

It is generated from these files:
	business.proto

It has these top-level messages:
	BusinessRequest
	BusinessResponse
*/
package business

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "microService/proto/query"
import _ "microService/proto/query"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Business service

type BusinessService interface {
	Search(ctx context.Context, in *BusinessRequest, opts ...client.CallOption) (*BusinessResponse, error)
}

type businessService struct {
	c    client.Client
	name string
}

func NewBusinessService(name string, c client.Client) BusinessService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "business"
	}
	return &businessService{
		c:    c,
		name: name,
	}
}

func (c *businessService) Search(ctx context.Context, in *BusinessRequest, opts ...client.CallOption) (*BusinessResponse, error) {
	req := c.c.NewRequest(c.name, "Business.Search", in)
	out := new(BusinessResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Business service

type BusinessHandler interface {
	Search(context.Context, *BusinessRequest, *BusinessResponse) error
}

func RegisterBusinessHandler(s server.Server, hdlr BusinessHandler, opts ...server.HandlerOption) {
	type business interface {
		Search(ctx context.Context, in *BusinessRequest, out *BusinessResponse) error
	}
	type Business struct {
		business
	}
	h := &businessHandler{hdlr}
	s.Handle(s.NewHandler(&Business{h}, opts...))
}

type businessHandler struct {
	BusinessHandler
}

func (h *businessHandler) Search(ctx context.Context, in *BusinessRequest, out *BusinessResponse) error {
	return h.BusinessHandler.Search(ctx, in, out)
}
