// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datastore.proto

package datastore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import query "microService/proto/query"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DatastoreRequest struct {
	Req                  *query.Request `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DatastoreRequest) Reset()         { *m = DatastoreRequest{} }
func (m *DatastoreRequest) String() string { return proto.CompactTextString(m) }
func (*DatastoreRequest) ProtoMessage()    {}
func (*DatastoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datastore_ab2bfa696ec253dd, []int{0}
}
func (m *DatastoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatastoreRequest.Unmarshal(m, b)
}
func (m *DatastoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatastoreRequest.Marshal(b, m, deterministic)
}
func (dst *DatastoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatastoreRequest.Merge(dst, src)
}
func (m *DatastoreRequest) XXX_Size() int {
	return xxx_messageInfo_DatastoreRequest.Size(m)
}
func (m *DatastoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DatastoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DatastoreRequest proto.InternalMessageInfo

func (m *DatastoreRequest) GetReq() *query.Request {
	if m != nil {
		return m.Req
	}
	return nil
}

type SaveRequest struct {
	Req                  *query.Request `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Recipe               string         `protobuf:"bytes,2,opt,name=recipe,proto3" json:"recipe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datastore_ab2bfa696ec253dd, []int{1}
}
func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (dst *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(dst, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetReq() *query.Request {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *SaveRequest) GetRecipe() string {
	if m != nil {
		return m.Recipe
	}
	return ""
}

type SaveResponse struct {
	Rsp                  string   `protobuf:"bytes,1,opt,name=rsp,proto3" json:"rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datastore_ab2bfa696ec253dd, []int{2}
}
func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (dst *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(dst, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetRsp() string {
	if m != nil {
		return m.Rsp
	}
	return ""
}

type DatastoreResponse struct {
	Rsp                  string   `protobuf:"bytes,1,opt,name=rsp,proto3" json:"rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatastoreResponse) Reset()         { *m = DatastoreResponse{} }
func (m *DatastoreResponse) String() string { return proto.CompactTextString(m) }
func (*DatastoreResponse) ProtoMessage()    {}
func (*DatastoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datastore_ab2bfa696ec253dd, []int{3}
}
func (m *DatastoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatastoreResponse.Unmarshal(m, b)
}
func (m *DatastoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatastoreResponse.Marshal(b, m, deterministic)
}
func (dst *DatastoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatastoreResponse.Merge(dst, src)
}
func (m *DatastoreResponse) XXX_Size() int {
	return xxx_messageInfo_DatastoreResponse.Size(m)
}
func (m *DatastoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatastoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatastoreResponse proto.InternalMessageInfo

func (m *DatastoreResponse) GetRsp() string {
	if m != nil {
		return m.Rsp
	}
	return ""
}

func init() {
	proto.RegisterType((*DatastoreRequest)(nil), "DatastoreRequest")
	proto.RegisterType((*SaveRequest)(nil), "SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "SaveResponse")
	proto.RegisterType((*DatastoreResponse)(nil), "DatastoreResponse")
}

func init() { proto.RegisterFile("datastore.proto", fileDescriptor_datastore_ab2bfa696ec253dd) }

var fileDescriptor_datastore_ab2bfa696ec253dd = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x1b, 0x2b, 0x81, 0x4c, 0x2b, 0xb6, 0x73, 0x90, 0x92, 0x53, 0x58, 0x28, 0xf6, 0x20,
	0x13, 0xac, 0x27, 0xef, 0x82, 0x27, 0x2f, 0xc9, 0x1f, 0x70, 0x8d, 0x83, 0x06, 0xb4, 0xbb, 0x99,
	0xdd, 0x16, 0xfc, 0xf7, 0x92, 0xdd, 0x2a, 0xc1, 0xe0, 0xad, 0xb7, 0x5d, 0xe6, 0xbd, 0x6f, 0xde,
	0x1b, 0xb8, 0x7c, 0xd5, 0x5e, 0x3b, 0x6f, 0x84, 0xc9, 0x8a, 0xf1, 0x26, 0xbf, 0xf9, 0x6c, 0x1b,
	0x31, 0x35, 0xcb, 0xa1, 0x6d, 0xf8, 0xd1, 0x7c, 0xe8, 0xdd, 0x5b, 0x19, 0x26, 0x65, 0xb7, 0x67,
	0xf9, 0x2a, 0x85, 0xbb, 0x3d, 0x3b, 0x1f, 0xd5, 0xea, 0x09, 0x16, 0x0f, 0x3f, 0x80, 0x2a, 0x4e,
	0xf0, 0x1e, 0xa6, 0xc2, 0xdd, 0x2a, 0x29, 0x92, 0xcd, 0x6c, 0x7b, 0x4d, 0x63, 0x5e, 0xf4, 0x52,
	0xe0, 0xd1, 0xd1, 0x55, 0xf5, 0x1e, 0xf5, 0x0c, 0xb3, 0x5a, 0x1f, 0x4e, 0x40, 0xc2, 0x2b, 0x48,
	0x85, 0x9b, 0xd6, 0xf2, 0xea, 0xac, 0x48, 0x36, 0x59, 0x75, 0xfc, 0xa9, 0x02, 0xe6, 0x71, 0x83,
	0xb3, 0x66, 0xe7, 0x18, 0x17, 0x30, 0x15, 0x67, 0xc3, 0x8a, 0xac, 0xea, 0x9f, 0x6a, 0x0d, 0xcb,
	0x41, 0xa5, 0xff, 0x64, 0x5b, 0x86, 0xec, 0x57, 0x86, 0xb7, 0x90, 0xd6, 0xac, 0xa5, 0x79, 0xc7,
	0x25, 0xfd, 0xbd, 0x47, 0x8e, 0x34, 0xe2, 0xa9, 0x09, 0xae, 0xe1, 0xbc, 0x0f, 0x82, 0x73, 0x1a,
	0x34, 0xce, 0x2f, 0x68, 0x98, 0x4e, 0x4d, 0x5e, 0xd2, 0xd0, 0xf0, 0xee, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x78, 0x6e, 0x4b, 0xa8, 0xa8, 0x01, 0x00, 0x00,
}
