// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: datastore.proto

/*
Package datastore is a generated protocol buffer package.

It is generated from these files:
	datastore.proto

It has these top-level messages:
	DatastoreRequest
	SaveRequest
	SaveResponse
	DatastoreResponse
*/
package datastore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "microService/proto/query"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Datastore service

type DatastoreService interface {
	Search(ctx context.Context, in *DatastoreRequest, opts ...client.CallOption) (*DatastoreResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error)
}

type datastoreService struct {
	c    client.Client
	name string
}

func NewDatastoreService(name string, c client.Client) DatastoreService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "datastore"
	}
	return &datastoreService{
		c:    c,
		name: name,
	}
}

func (c *datastoreService) Search(ctx context.Context, in *DatastoreRequest, opts ...client.CallOption) (*DatastoreResponse, error) {
	req := c.c.NewRequest(c.name, "Datastore.Search", in)
	out := new(DatastoreResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreService) Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error) {
	req := c.c.NewRequest(c.name, "Datastore.Save", in)
	out := new(SaveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Datastore service

type DatastoreHandler interface {
	Search(context.Context, *DatastoreRequest, *DatastoreResponse) error
	Save(context.Context, *SaveRequest, *SaveResponse) error
}

func RegisterDatastoreHandler(s server.Server, hdlr DatastoreHandler, opts ...server.HandlerOption) {
	type datastore interface {
		Search(ctx context.Context, in *DatastoreRequest, out *DatastoreResponse) error
		Save(ctx context.Context, in *SaveRequest, out *SaveResponse) error
	}
	type Datastore struct {
		datastore
	}
	h := &datastoreHandler{hdlr}
	s.Handle(s.NewHandler(&Datastore{h}, opts...))
}

type datastoreHandler struct {
	DatastoreHandler
}

func (h *datastoreHandler) Search(ctx context.Context, in *DatastoreRequest, out *DatastoreResponse) error {
	return h.DatastoreHandler.Search(ctx, in, out)
}

func (h *datastoreHandler) Save(ctx context.Context, in *SaveRequest, out *SaveResponse) error {
	return h.DatastoreHandler.Save(ctx, in, out)
}
