// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package microService_proto_query

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_Diet int32

const (
	Request_UNKNOWN_DIET Request_Diet = 0
	Request_BALANCED     Request_Diet = 1
	Request_HIGHPROTIEN  Request_Diet = 2
	Request_HIGHFIBER    Request_Diet = 3
)

var Request_Diet_name = map[int32]string{
	0: "UNKNOWN_DIET",
	1: "BALANCED",
	2: "HIGHPROTIEN",
	3: "HIGHFIBER",
}
var Request_Diet_value = map[string]int32{
	"UNKNOWN_DIET": 0,
	"BALANCED":     1,
	"HIGHPROTIEN":  2,
	"HIGHFIBER":    3,
}

func (x Request_Diet) String() string {
	return proto.EnumName(Request_Diet_name, int32(x))
}
func (Request_Diet) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_request_b922efb3124e5f02, []int{0, 0}
}

type Request_Health int32

const (
	Request_UNKNOWN_HEALTH Request_Health = 0
	Request_PEANUTFREE     Request_Health = 1
	Request_TREENUTFREE    Request_Health = 2
)

var Request_Health_name = map[int32]string{
	0: "UNKNOWN_HEALTH",
	1: "PEANUTFREE",
	2: "TREENUTFREE",
}
var Request_Health_value = map[string]int32{
	"UNKNOWN_HEALTH": 0,
	"PEANUTFREE":     1,
	"TREENUTFREE":    2,
}

func (x Request_Health) String() string {
	return proto.EnumName(Request_Health_name, int32(x))
}
func (Request_Health) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_request_b922efb3124e5f02, []int{0, 1}
}

// request message structure
type Request struct {
	Q                    string         `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	R                    string         `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	From                 int32          `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32          `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	Ingr                 string         `protobuf:"bytes,5,opt,name=ingr,proto3" json:"ingr,omitempty"`
	Diet                 Request_Diet   `protobuf:"varint,6,opt,name=diet,proto3,enum=microService.proto.query.Request_Diet" json:"diet,omitempty"`
	Health               Request_Health `protobuf:"varint,7,opt,name=health,proto3,enum=microService.proto.query.Request_Health" json:"health,omitempty"`
	Calories             string         `protobuf:"bytes,8,opt,name=calories,proto3" json:"calories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_b922efb3124e5f02, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *Request) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *Request) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Request) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Request) GetIngr() string {
	if m != nil {
		return m.Ingr
	}
	return ""
}

func (m *Request) GetDiet() Request_Diet {
	if m != nil {
		return m.Diet
	}
	return Request_UNKNOWN_DIET
}

func (m *Request) GetHealth() Request_Health {
	if m != nil {
		return m.Health
	}
	return Request_UNKNOWN_HEALTH
}

func (m *Request) GetCalories() string {
	if m != nil {
		return m.Calories
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "microService.proto.query.Request")
	proto.RegisterEnum("microService.proto.query.Request_Diet", Request_Diet_name, Request_Diet_value)
	proto.RegisterEnum("microService.proto.query.Request_Health", Request_Health_name, Request_Health_value)
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_request_b922efb3124e5f02) }

var fileDescriptor_request_b922efb3124e5f02 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0x41, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xd9, 0x52, 0x0a, 0xcc, 0x1f, 0xfa, 0x6f, 0xe6, 0xb4, 0xf1, 0x60, 0x08, 0x27, 0x0e,
	0xa6, 0x07, 0x3d, 0x9b, 0x58, 0x64, 0x4b, 0x1b, 0x49, 0x21, 0x6b, 0x89, 0x47, 0x83, 0xb8, 0xc2,
	0x26, 0x85, 0xb5, 0xcb, 0x62, 0xe2, 0x57, 0xf0, 0x53, 0x9b, 0x6e, 0xc1, 0xa3, 0xf1, 0x36, 0xef,
	0xed, 0xfe, 0xde, 0xbc, 0x81, 0xbe, 0x16, 0xe5, 0x51, 0x1c, 0x4c, 0xf8, 0xae, 0x95, 0x51, 0x78,
	0xb9, 0x93, 0x6b, 0xad, 0x1e, 0x85, 0xfe, 0x90, 0x6b, 0x31, 0x55, 0xc5, 0x6a, 0xbf, 0xa9, 0x5f,
	0xc2, 0xf2, 0x28, 0xf4, 0xe7, 0xf0, 0xab, 0x09, 0x6d, 0x5e, 0x13, 0xd8, 0x03, 0x52, 0x52, 0x32,
	0x20, 0xa3, 0x2e, 0x27, 0x65, 0xa5, 0x34, 0x75, 0x6a, 0xa5, 0x11, 0xc1, 0x7d, 0xd3, 0x6a, 0x47,
	0x9b, 0x03, 0x32, 0x6a, 0x71, 0x3b, 0xa3, 0x0f, 0x8e, 0x51, 0xd4, 0xb5, 0x8e, 0x63, 0x54, 0xf5,
	0x47, 0xee, 0x37, 0x9a, 0xb6, 0x2c, 0x64, 0x67, 0xbc, 0x03, 0xf7, 0x55, 0x0a, 0x43, 0xbd, 0x01,
	0x19, 0xf9, 0xd7, 0x57, 0xe1, 0xef, 0x75, 0xc2, 0x53, 0x95, 0x70, 0x22, 0x85, 0xe1, 0x96, 0xc4,
	0x18, 0xbc, 0xad, 0x58, 0x15, 0x66, 0x4b, 0xdb, 0x36, 0x23, 0xfc, 0x6b, 0x46, 0x62, 0x29, 0x7e,
	0xa2, 0xf1, 0x02, 0x3a, 0xeb, 0x55, 0xa1, 0xb4, 0x14, 0x07, 0xda, 0xb1, 0x0d, 0x7f, 0xf4, 0x30,
	0x06, 0xb7, 0xda, 0x88, 0x01, 0xf4, 0x96, 0xd9, 0x43, 0x36, 0x7f, 0xca, 0x9e, 0x27, 0x29, 0xcb,
	0x83, 0x06, 0xf6, 0xa0, 0x33, 0x8e, 0x66, 0x51, 0x76, 0xcf, 0x26, 0x01, 0xc1, 0xff, 0xf0, 0x2f,
	0x49, 0xa7, 0xc9, 0x82, 0xcf, 0xf3, 0x94, 0x65, 0x81, 0x83, 0x7d, 0xe8, 0x56, 0x46, 0x9c, 0x8e,
	0x19, 0x0f, 0x9a, 0xc3, 0x5b, 0xf0, 0xea, 0xad, 0x88, 0xe0, 0x9f, 0x93, 0x12, 0x16, 0xcd, 0xf2,
	0x24, 0x68, 0xa0, 0x0f, 0xb0, 0x60, 0x51, 0xb6, 0xcc, 0x63, 0xce, 0x58, 0x9d, 0x96, 0x73, 0xc6,
	0xce, 0x86, 0xf3, 0xe2, 0xd9, 0x33, 0x6e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x66, 0x5a, 0x43,
	0x4e, 0xc4, 0x01, 0x00, 0x00,
}
